### ISSUE TITLE
en.lhd.extension.2015.nt is not a valid nt file

### ISSUE THREAD

**Issue by oroszgy** [KIZI/LinkedHypernymsDataset#5] opened 2015-08-25 14:01 UTC
The file is not a valid nt file.

When I try to parse it with rdflib (Python),

```
import rdflib
mygraph = rdflib.Graph()
mygraph.parse("./en.lhd.extension.2015.nt", format="nt")
```

 it throws an exception:

```
ParseError: Invalid line: '<http://dbpedia.org/resource/ 44_(band)> <http://purl.org/linguistics/gold/hypernym> <http://dbpedia.org/resource/Supergroup> .'
```

**Comment by kliegr** [comment] 2015-08-27 06:24
This indeed looks like an invalid uri. Spaces are not allowed in URIs as per RFC 2396. The same problem applies to the 2015 inference dataset.

**Comment by kliegr** [comment] 2015-09-17 12:03
The problem is that the + sign gets erroneously coded as space. This is planned to be fixed for the next LHD release. 

Temporary solution is to preprocess the data with the following command
`cat en.lhd.extension.2015.nt | perl -ne 's/ (?=.*> <http:\/\/[wp])/+/g; print;' > en.lhd.extension.2015.fixed.nt`
This assumes that there is no other condition under which a space can occur in resource uris.

**Comment by kliegr** [comment] 2015-09-18 11:02
The patched files are available for download from http://ner.vse.cz/datasets/linkedhypernyms/.
@oroszgy   Your script now parses the file successfully.
@propi I am keeping the issue open until it is fixed in the framework.

**Comment by oroszgy** [comment] 2015-09-21 06:49
Thanks guys, I really like your work!

**Comment by joernhees** [comment] 2015-11-26 14:21
http://downloads.dbpedia.org/2015-04/core-i18n/en/instance_types_lhd_ext_en.nt.bz2 and http://downloads.dbpedia.org/2015-04/core-i18n/en/instance_types_lhd_dbo_en.nt.bz2 are still broken, maybe you could trigger an update there as well?

**Comment by kliegr** [comment] 2015-11-27 13:38
Request for update of the DBpedia mirror has been just sent.

**Comment by joernhees** [comment] 2015-11-27 14:41
:+1: cool, thanks

and btw: thanks for the cool dataset :)

**Closed as completed** 2016-03-02 16:07 UTC
